site_name: Jitsi Meet
theme:
   name: material
   features:
      - navigation.tabs
   palette:
      primary: indigo
      accent: indigo
   favicon: assets/jitsiFavcon.png
   logo: assets/jitsiLogo.png
nav:
   - Início: ./index.md
   - Apresentações:
        - Primeira Apresentação: ./apresentacoes/apresentacao1.md
        - Segunda Apresentação: ./apresentacoes/apresentacao2.md
        - Terceira Apresentação: ./apresentacoes/apresentacao3.md
        - Quarta Apresentação: ./apresentacoes/apresentacao4.md
   - Planejamento:
        - Metodologia: ./planejamento/metodologia.md
        - Ferramentas Utilizadas: ./planejamento/ferramentas.md
        - Cronograma: ./planejamento/cronograma.md
        - Heatmap: ./planejamento/heatmap.md
        - Políticas: ./planejamento/politicas.md
   - Pré-Rastreabilidade:
        - Rich Picture: ./preRastreabilidade/richPicture.md
   - Elicitação de Requisitos:
        - Análise de Protocolo: ./elicitacao/analiseProtocolo.md
        - Brainstorming: ./elicitacao/brainstorming.md
        - Personas e Storytelling: ./elicitacao/personas.md
        - Requisitos Elicitados: ./elicitacao/requisitoselicitados.md
   - Modelagem de Requisitos:
        - Cenários: ./modelagem/cenarios.md
        - Léxico: ./modelagem/lexico.md
        - Use Case: ./modelagem/useCase.md
        - Especificação Suplementar: ./modelagem/especificacaoSuplementar.md
        - NFR Framework: ./modelagem/nfr.md
        - Ágil:
             - Backlog: ./modelagem/agil/backlog.md
             - Histórias de Usuário: ./modelagem/agil/historiasDeUsuario.md
   - Análise de Requisitos:
        - Verificação: ./analiseDeRequisitos/verificacao.md
        - Validação:
             - Protótipo: ./analiseDeRequisitos/validacao/prototipo

markdown_extensions:
   - attr_list
