site_name: Jitsi Meet
theme:
   name: material
   features:
      - navigation.tabs
   palette:
      primary: indigo
      accent: indigo
   favicon: assets/jitsiFavcon.png
   logo: assets/jitsiLogo.png
nav:
   - Início: ./index.md
   - Apresentações:
        - Primeira Apresentação: ./apresentacoes/apresentacao1.md
   - Planejamento:
         - Metodologia: ./planejamento/metodologia.md
         - Ferramentas Utilizadas: ./planejamento/ferramentas.md
         - Cronograma: ./planejamento/cronograma.md
         - Heatmap: ./planejamento/heatmap.md
         - Políticas: ./planejamento/politicas.md
   - Pré-Rastreabilidade:
         - Rich Picture: ./preRastreabilidade/richPicture.md
   - Elicitação - Técnicas e Priorização:
         - Brainstorming: ./elicitacao/brainstorming.md
         - Personas e Storytelling: ./elicitacao/personas.md

markdown_extensions:
  - attr_list